{{- if .Values.deployment.containers.env.secret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- if .Values.secret.encrypteddata }}
  {{ toYaml .Values.secret.encrypteddata | indent 2 }}
    {{- end }}
{{- end }}